export const hex = {
	black: "000000",
	red: "800000",
	green: "008000",
	yellow: "808000",
	blue: "000080",
	magenta: "800080",
	cyan: "008080",
	white: "c0c0c0",
	blackBright: "808080",
	redBright: "ff0000",
	greenBright: "00ff00",
	yellowBright: "ffff00",
	blueBright: "0000ff",
	magentaBright: "ff00ff",
	cyanBright: "00ffff",
	whiteBright: "ffffff",
	discordBlue: "7289da",
	orange: "e77c02",
} as const;
export const mcc = {
	reset: "§r",
	black: "§0",
	red: "§4",
	green: "§2",
	yellow: "§6",
	blue: "§1",
	magenta: "§5",
	cyan: "§3",
	white: "§7",
	blackBright: "§8",
	redBright: "§c",
	greenBright: "§a",
	yellowBright: "§e",
	blueBright: "§9",
	magentaBright: "§d",
	cyanBright: "§b",
	whiteBright: "§f",
} as const;
export const mc = {
	black: "black",
	red: "dark_red",
	green: "dark_green",
	yellow: "gold",
	blue: "dark_blue",
	magenta: "dark_purple",
	cyan: "dark_aqua",
	white: "gray",
	blackBright: "dark_gray",
	redBright: "red",
	greenBright: "green",
	yellowBright: "yellow",
	blueBright: "blue",
	magentaBright: "light_purple",
	cyanBright: "aqua",
	whiteBright: "white",
} as const;
